name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Her gün gece yarısı çalıştır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit and Push
        run: |
          git add dist/
          git commit -m "Update snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
